import type { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateLocations1786811204629 implements MigrationInterface {
    name = 'CreateLocations1786811204629';

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(
            `CREATE TABLE "locations" ("id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL, "zipCode" character varying(5) NOT NULL, "city" character varying(180) NOT NULL, "stateCode" character varying(2) NOT NULL, "stateName" character varying(100) NOT NULL, "county" character varying(100), "location" geography(Point,4326) NOT NULL, "accuracy" smallint, CONSTRAINT "PK_7cc1c9e3853b94816c094825e74" PRIMARY KEY ("id"))`,
        );
        await queryRunner.query(
            `CREATE INDEX "IDX_LOCATION_POINT" ON "locations" USING gist ("location") `,
        );
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_LOCATION_POINT"`);
        await queryRunner.query(`DROP TABLE "locations"`);
    }
}
