FROM node:24-alpine

ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

RUN corepack enable

WORKDIR /workspace

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml nx.json tsconfig.base.json ./

COPY apps/api/package.json apps/api/package.json
COPY apps/web/package.json apps/web/package.json
COPY apps/api-e2e/package.json apps/api-e2e/package.json
COPY apps/web-e2e/package.json apps/web-e2e/package.json

RUN pnpm install --frozen-lockfile --ignore-scripts

COPY apps/api apps/api

CMD ["pnpm", "--filter", "@geocoding/api", "run", "migration:run"]